Woops, Telegram returns 403 Forbidden, not 401 Unauthorized, if the bot tries to send a message to a user that doesn't have an open chat with the bot.
2018-08-31 07:39:50,498 ERROR loop.py:81] Ignoring uncaught error while dispatching:
Traceback (most recent call last):
  File "metabot/lib/python3.5/site-packages/ntelebot/loop.py", line 79, in run
    dispatcher(bot, update)
  File "metabot/metabot/multibot.py", line 103, in __call__
    ret = moddispatch(ctx, botconfig[modname])
  File "metabot/metabot/modules/groups.py", line 36, in moddispatch
    return default(ctx, modconf)
  File "metabot/metabot/modules/groups.py", line 66, in default
    return msg.reply(ctx)
  File "metabot/metabot/util/msgbuilder.py", line 63, in reply
    disable_web_page_preview=True)
  File "metabot/lib/python3.5/site-packages/ntelebot/preprocess.py", line 115, in reply_html
    return self.reply_text(text, *args, **kwargs)
  File "metabot/lib/python3.5/site-packages/ntelebot/preprocess.py", line 143, in reply_text
    return self.bot.send_message(chat_id=self.user['id'], text=text, **kwargs)
  File "metabot/lib/python3.5/site-packages/ntelebot/bot.py", line 50, in __call__
    raise ntelebot.errors.Error(data)
ntelebot.errors.Error: {'error_code': 403, 'description': "Forbidden: bot can't initiate conversation with a user", 'ok': False}